use excel_skill::ops::betting_optimizer::{BettingOptimizerEntry, BettingOptimizerRequest, solve_betting_adjustment};
fn main() {
    let request = BettingOptimizerRequest::new(
        vec![
            BettingOptimizerEntry::new("01", 40),
            BettingOptimizerEntry::new("02", 80),
            BettingOptimizerEntry::new("03", 50),
            BettingOptimizerEntry::new("04", 70),
            BettingOptimizerEntry::new("05", 70),
            BettingOptimizerEntry::new("06", 70),
            BettingOptimizerEntry::new("07", 50),
            BettingOptimizerEntry::new("08", 35),
            BettingOptimizerEntry::new("09", 10),
            BettingOptimizerEntry::new("10", 15),
            BettingOptimizerEntry::new("11", 50),
            BettingOptimizerEntry::new("12", 45),
            BettingOptimizerEntry::new("13", 70),
            BettingOptimizerEntry::new("14", 50),
            BettingOptimizerEntry::new("15", 60),
            BettingOptimizerEntry::new("16", 70),
            BettingOptimizerEntry::new("17", 80),
            BettingOptimizerEntry::new("18", 70),
            BettingOptimizerEntry::new("19", 50),
            BettingOptimizerEntry::new("20", 15),
            BettingOptimizerEntry::new("21", 60),
            BettingOptimizerEntry::new("22", 15),
            BettingOptimizerEntry::new("23", 50),
            BettingOptimizerEntry::new("24", 45),
            BettingOptimizerEntry::new("25", 70),
            BettingOptimizerEntry::new("26", 50),
            BettingOptimizerEntry::new("27", 60),
            BettingOptimizerEntry::new("28", 70),
            BettingOptimizerEntry::new("29", 80),
            BettingOptimizerEntry::new("30", 60),
            BettingOptimizerEntry::new("31", 50),
            BettingOptimizerEntry::new("32", 45),
            BettingOptimizerEntry::new("33", 0),
            BettingOptimizerEntry::new("34", 25),
            BettingOptimizerEntry::new("35", 50),
            BettingOptimizerEntry::new("36", 50),
            BettingOptimizerEntry::new("37", 40),
            BettingOptimizerEntry::new("38", 70),
            BettingOptimizerEntry::new("39", 50),
            BettingOptimizerEntry::new("40", 60),
            BettingOptimizerEntry::new("41", 50),
            BettingOptimizerEntry::new("42", 60),
            BettingOptimizerEntry::new("43", 50),
            BettingOptimizerEntry::new("44", 55),
            BettingOptimizerEntry::new("45", 0),
            BettingOptimizerEntry::new("46", 45),
            BettingOptimizerEntry::new("47", 50),
            BettingOptimizerEntry::new("48", 40),
            BettingOptimizerEntry::new("49", 40),
        ],
        47.0,
        0.02,
        1000.0,
        19,
    );
    let solution = solve_betting_adjustment(&request).unwrap();
    println!("refund={} total={} max_loss={} loss_count={}", solution.total_refund, solution.total_adjusted_stake, solution.max_loss, solution.loss_count);
    for entry in solution.entries.iter().filter(|entry| entry.refund_amount > 0) {
        println!("{} {} -> {} refund {} pnl {}", entry.label, entry.original_stake, entry.adjusted_stake, entry.refund_amount, entry.pnl_value);
    }
}
