#[path = "analyze.rs"]
pub mod analyze;
#[path = "append.rs"]
pub mod append;
#[path = "capacity_assessment.rs"]
pub mod capacity_assessment;
#[path = "capacity_assessment_excel_report.rs"]
pub mod capacity_assessment_excel_report;
#[path = "capacity_assessment_from_inventory.rs"]
pub mod capacity_assessment_from_inventory;
#[path = "cast.rs"]
pub mod cast;
#[path = "chart_svg.rs"]
pub mod chart_svg;
#[path = "cluster_kmeans.rs"]
pub mod cluster_kmeans;
#[path = "correlation_analysis.rs"]
pub mod correlation_analysis;
#[path = "decision_assistant.rs"]
pub mod decision_assistant;
#[path = "deduplicate_by_key.rs"]
pub mod deduplicate_by_key;
#[path = "derive.rs"]
pub mod derive;
#[path = "diagnostics_report.rs"]
pub mod diagnostics_report;
#[path = "diagnostics_report_excel_report.rs"]
pub mod diagnostics_report_excel_report;
#[path = "distinct_rows.rs"]
pub mod distinct_rows;
#[path = "distribution_analysis.rs"]
pub mod distribution_analysis;
#[path = "excel_chart_writer.rs"]
pub mod excel_chart_writer;
#[path = "export.rs"]
pub mod export;
#[path = "fill_lookup.rs"]
pub mod fill_lookup;
#[path = "fill_missing_values.rs"]
pub mod fill_missing_values;
#[path = "filter.rs"]
pub mod filter;
#[path = "format_table_for_export.rs"]
pub mod format_table_for_export;
#[path = "group.rs"]
pub mod group;
#[path = "join.rs"]
pub mod join;
#[path = "linear_regression.rs"]
pub mod linear_regression;
#[path = "logistic_regression.rs"]
pub mod logistic_regression;
#[path = "lookup_values.rs"]
pub mod lookup_values;
#[path = "model_output.rs"]
pub mod model_output;
#[path = "model_prep.rs"]
pub mod model_prep;
#[path = "multi_table_plan.rs"]
pub mod multi_table_plan;
#[path = "normalize_text.rs"]
pub mod normalize_text;
#[path = "outlier_detection.rs"]
pub mod outlier_detection;
#[path = "parse_datetime.rs"]
pub mod parse_datetime;
#[path = "pivot.rs"]
pub mod pivot;
#[path = "preview.rs"]
pub mod preview;
#[path = "rename.rs"]
pub mod rename;
#[path = "report_delivery.rs"]
pub mod report_delivery;
#[path = "select.rs"]
pub mod select;
#[path = "semantic.rs"]
pub mod semantic;
#[path = "sort.rs"]
pub mod sort;
#[path = "ssh_inventory.rs"]
pub mod ssh_inventory;
#[path = "stat_summary.rs"]
pub mod stat_summary;
#[path = "summary.rs"]
pub mod summary;
#[path = "table_links.rs"]
pub mod table_links;
#[path = "table_workflow.rs"]
pub mod table_workflow;
#[path = "top_n.rs"]
pub mod top_n;
#[path = "trend_analysis.rs"]
pub mod trend_analysis;
#[path = "window.rs"]
pub mod window;

#[path = "foundation/capability_router.rs"]
pub mod capability_router;
#[path = "foundation/evidence_assembler.rs"]
pub mod evidence_assembler;
// 2026-04-12 CST: Restored these exports because the knowledge roaming foundation
// still depends on the shared bundle / ingestion / repository modules at the
// bottom layer. Purpose: align the public foundation entrypoint with the actual
// workspace modules so repository evidence hygiene diagnostics can compile again.
#[path = "foundation/knowledge_bundle.rs"]
pub mod knowledge_bundle;
#[path = "foundation/knowledge_graph_store.rs"]
pub mod knowledge_graph_store;
#[path = "foundation/knowledge_ingestion.rs"]
pub mod knowledge_ingestion;
#[path = "foundation/knowledge_record.rs"]
pub mod knowledge_record;
#[path = "foundation/knowledge_repository.rs"]
pub mod knowledge_repository;
#[path = "foundation/metadata_constraint.rs"]
pub mod metadata_constraint;
#[path = "foundation/metadata_registry.rs"]
pub mod metadata_registry;
#[path = "foundation/metadata_scope_resolver.rs"]
pub mod metadata_scope_resolver;
#[path = "foundation/navigation_pipeline.rs"]
pub mod navigation_pipeline;
#[path = "foundation/ontology_schema.rs"]
pub mod ontology_schema;
#[path = "foundation/ontology_store.rs"]
pub mod ontology_store;
#[path = "foundation/retrieval_engine.rs"]
pub mod retrieval_engine;
#[path = "foundation/roaming_engine.rs"]
pub mod roaming_engine;

// 2026-04-12 CST: 这里移除失效的 foundation 模块导出，原因是当前分支已不再包含
// `knowledge_bundle / knowledge_ingestion / knowledge_repository` 文件，但入口仍在导出它们，导致 crate 在模块加载阶段直接编译失败。
// 目的：先恢复当前 foundation 分支的可编译状态，再继续推进本轮 source_ref 结构诊断，不在这里重建缺失模块或跨线重构。
#[path = "foundation/metadata_schema.rs"]
pub mod metadata_schema;
#[path = "foundation/metadata_validator.rs"]
pub mod metadata_validator;
#[path = "foundation/repository_metadata_audit.rs"]
pub mod repository_metadata_audit;
