// 2026-03-31 CST: 这里建立 foundation 模块边界，原因是底座能力与股票业务能力已经开始在 catalog / dispatcher 层串台。
// 目的：把 Excel、统计诊断、建模、报表与容量评估明确归到通用底座域，后续新增通用能力默认先进入这里。
#[path = "preview.rs"]
pub mod preview;
#[path = "select.rs"]
pub mod select;
#[path = "filter.rs"]
pub mod filter;
#[path = "distinct_rows.rs"]
pub mod distinct_rows;
#[path = "deduplicate_by_key.rs"]
pub mod deduplicate_by_key;
#[path = "cast.rs"]
pub mod cast;
#[path = "normalize_text.rs"]
pub mod normalize_text;
#[path = "rename.rs"]
pub mod rename;
#[path = "format_table_for_export.rs"]
pub mod format_table_for_export;
#[path = "fill_lookup.rs"]
pub mod fill_lookup;
#[path = "fill_missing_values.rs"]
pub mod fill_missing_values;
#[path = "pivot.rs"]
pub mod pivot;
#[path = "parse_datetime.rs"]
pub mod parse_datetime;
#[path = "lookup_values.rs"]
pub mod lookup_values;
#[path = "window.rs"]
pub mod window;
#[path = "derive.rs"]
pub mod derive;
#[path = "export.rs"]
pub mod export;
#[path = "report_delivery.rs"]
pub mod report_delivery;
#[path = "chart_svg.rs"]
pub mod chart_svg;
#[path = "excel_chart_writer.rs"]
pub mod excel_chart_writer;
#[path = "group.rs"]
pub mod group;
#[path = "sort.rs"]
pub mod sort;
#[path = "top_n.rs"]
pub mod top_n;
#[path = "join.rs"]
pub mod join;
#[path = "append.rs"]
pub mod append;
#[path = "summary.rs"]
pub mod summary;
#[path = "analyze.rs"]
pub mod analyze;
#[path = "semantic.rs"]
pub mod semantic;
#[path = "table_links.rs"]
pub mod table_links;
#[path = "table_workflow.rs"]
pub mod table_workflow;
#[path = "multi_table_plan.rs"]
pub mod multi_table_plan;
#[path = "stat_summary.rs"]
pub mod stat_summary;
#[path = "correlation_analysis.rs"]
pub mod correlation_analysis;
#[path = "outlier_detection.rs"]
pub mod outlier_detection;
#[path = "distribution_analysis.rs"]
pub mod distribution_analysis;
#[path = "trend_analysis.rs"]
pub mod trend_analysis;
#[path = "diagnostics_report.rs"]
pub mod diagnostics_report;
#[path = "diagnostics_report_excel_report.rs"]
pub mod diagnostics_report_excel_report;
#[path = "capacity_assessment.rs"]
pub mod capacity_assessment;
#[path = "capacity_assessment_from_inventory.rs"]
pub mod capacity_assessment_from_inventory;
#[path = "capacity_assessment_excel_report.rs"]
pub mod capacity_assessment_excel_report;
#[path = "ssh_inventory.rs"]
pub mod ssh_inventory;
#[path = "linear_regression.rs"]
pub mod linear_regression;
#[path = "model_prep.rs"]
pub mod model_prep;
#[path = "model_output.rs"]
pub mod model_output;
#[path = "logistic_regression.rs"]
pub mod logistic_regression;
#[path = "cluster_kmeans.rs"]
pub mod cluster_kmeans;
#[path = "decision_assistant.rs"]
pub mod decision_assistant;
