pub const FOUNDATION_TOOL_NAMES: &[&str] = &[
    "license_activate",
    "license_status",
    "license_deactivate",
    "open_workbook",
    "list_sheets",
    "inspect_sheet_range",
    "load_table_region",
    "normalize_table",
    "apply_header_schema",
    "get_session_state",
    "update_session_state",
    "preview_table",
    "select_columns",
    "normalize_text_columns",
    "rename_columns",
    "fill_missing_values",
    "distinct_rows",
    "deduplicate_by_key",
    "format_table_for_export",
    "fill_missing_from_lookup",
    "parse_datetime_columns",
    "lookup_values",
    "window_calculation",
    "filter_rows",
    "cast_column_types",
    "derive_columns",
    "group_and_aggregate",
    "pivot_table",
    "sort_rows",
    "top_n",
    "compose_workbook",
    "report_delivery",
    "build_chart",
    "export_chart_image",
    "export_csv",
    "export_excel",
    "export_excel_workbook",
    "join_tables",
    "suggest_table_links",
    "suggest_table_workflow",
    "suggest_multi_table_plan",
    "append_tables",
    "summarize_table",
    "analyze_table",
    "stat_summary",
    "correlation_analysis",
    "outlier_detection",
    "distribution_analysis",
    "trend_analysis",
    "diagnostics_report_excel_report",
    "diagnostics_report",
    "capacity_assessment",
    "capacity_assessment_from_inventory",
    "ssh_inventory",
    "capacity_assessment_excel_report",
    "linear_regression",
    "logistic_regression",
    "cluster_kmeans",
    "decision_assistant",
];

pub const STOCK_TOOL_NAMES: &[&str] = &[
    "technical_consultation_basic",
    "security_analysis_contextual",
    "security_analysis_fullstack",
    "security_decision_briefing",
    "security_position_plan_record",
    "security_record_position_adjustment",
    "security_committee_vote",
    // 2026-04-10 CST: 这里把 security_condition_review 注册进 stock tool 目录，原因是 Task 3 要把条件复核中枢暴露为正式 CLI Tool；
    // 目的：让 CLI / Skill / tool_catalog 都能发现这条投中复核入口，避免它继续停留在仅可内部调用的状态。
    "security_condition_review",
    // 2026-04-10 CST: 这里补 execution/review 两个正式 Tool 注册，原因是 Task 5 要把条件复核继续挂进执行与复盘主链；
    // 目的：让 CLI / Skill / tool_catalog 能发现这两个入口，避免测试和上层调用落到“tool unsupported”分支。
    "security_execution_record",
    "security_post_trade_review",
    "register_resonance_factor",
    "append_resonance_factor_series",
    "append_resonance_event_tags",
    "sync_template_resonance_factors",
    "bootstrap_resonance_template_factors",
    "evaluate_security_resonance",
    "security_analysis_resonance",
    "record_security_signal_snapshot",
    "backfill_security_signal_outcomes",
    "study_security_signal_analogs",
    "signal_outcome_research_summary",
    "security_decision_evidence_bundle",
    "security_decision_committee",
    "security_committee_member_agent",
    "security_chair_resolution",
    "security_feature_snapshot",
    "security_forward_outcome",
    "security_scorecard_refit",
    "security_scorecard_training",
    "security_decision_submit_approval",
    "security_decision_verify_package",
    "security_decision_package_revision",
    "security_record_post_meeting_conclusion",
    "import_stock_price_history",
    "sync_stock_price_history",
];

pub const TOOL_NAMES: &[&str] = &[
    "license_activate",
    "license_status",
    "license_deactivate",
    "open_workbook",
    "list_sheets",
    "inspect_sheet_range",
    "load_table_region",
    "normalize_table",
    "apply_header_schema",
    "get_session_state",
    "update_session_state",
    "preview_table",
    "select_columns",
    "normalize_text_columns",
    "rename_columns",
    "fill_missing_values",
    "distinct_rows",
    "deduplicate_by_key",
    "format_table_for_export",
    "fill_missing_from_lookup",
    "parse_datetime_columns",
    "lookup_values",
    "window_calculation",
    "filter_rows",
    "cast_column_types",
    "derive_columns",
    "group_and_aggregate",
    "pivot_table",
    "sort_rows",
    "top_n",
    "compose_workbook",
    "report_delivery",
    "build_chart",
    "export_chart_image",
    "export_csv",
    "export_excel",
    "export_excel_workbook",
    "join_tables",
    "suggest_table_links",
    "suggest_table_workflow",
    "suggest_multi_table_plan",
    "append_tables",
    "summarize_table",
    "analyze_table",
    "stat_summary",
    "correlation_analysis",
    "outlier_detection",
    "distribution_analysis",
    "trend_analysis",
    "technical_consultation_basic",
    "security_analysis_contextual",
    "security_analysis_fullstack",
    "security_decision_briefing",
    "security_position_plan_record",
    "security_record_position_adjustment",
    "security_committee_vote",
    // 2026-04-10 CST: 这里同步把 security_condition_review 注册进总 tool 目录，原因是主 catalog 需要与 stock 子目录保持一致；
    // 目的：避免出现 stock 模块已接线但 tool_catalog 总览缺项的目录漂移。
    "security_condition_review",
    // 2026-04-10 CST: 这里同步补 execution/review 两个 Tool 到总目录，原因是总目录必须与 stock 子目录保持一致；
    // 目的：避免 stock dispatcher 已接线但 tool_catalog 仍缺项，导致 CLI 发现场景和真实路由脱节。
    "security_execution_record",
    "security_post_trade_review",
    "register_resonance_factor",
    "append_resonance_factor_series",
    "append_resonance_event_tags",
    "sync_template_resonance_factors",
    "bootstrap_resonance_template_factors",
    "evaluate_security_resonance",
    "security_analysis_resonance",
    "record_security_signal_snapshot",
    "backfill_security_signal_outcomes",
    "study_security_signal_analogs",
    "signal_outcome_research_summary",
    "security_decision_evidence_bundle",
    "security_decision_committee",
    "security_committee_member_agent",
    "security_chair_resolution",
    "security_feature_snapshot",
    "security_forward_outcome",
    "security_scorecard_refit",
    "security_scorecard_training",
    "security_decision_submit_approval",
    "security_decision_verify_package",
    "security_decision_package_revision",
    "security_record_post_meeting_conclusion",
    "import_stock_price_history",
    "sync_stock_price_history",
    "diagnostics_report_excel_report",
    "diagnostics_report",
    "capacity_assessment",
    "capacity_assessment_from_inventory",
    "ssh_inventory",
    "capacity_assessment_excel_report",
    "linear_regression",
    "logistic_regression",
    "cluster_kmeans",
    "decision_assistant",
];

pub fn tool_names() -> &'static [&'static str] {
    TOOL_NAMES
}

pub fn foundation_tool_names() -> &'static [&'static str] {
    FOUNDATION_TOOL_NAMES
}

pub fn stock_tool_names() -> &'static [&'static str] {
    STOCK_TOOL_NAMES
}

pub fn is_supported_tool(tool_name: &str) -> bool {
    TOOL_NAMES.contains(&tool_name)
}

pub fn is_stock_tool(tool_name: &str) -> bool {
    STOCK_TOOL_NAMES.contains(&tool_name)
}
